import * as React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { API_URL } from '../../utils/constants';
import axios from 'axios';
import Order from '.';
import OrderContext from '../../context/OrderContext';

describe('Test Order', () => {
  let orderName;
  let orderItems;
  
  beforeEach(() => {
    //Arrange: Setup Order Context
    orderName = 'test-fun';
    orderItems = [
      { item: 'Test 1', quantity: 1 },
      { item: 'Test 2', quantity: 2 },
      { item: 'Test 3', quantity: 3 },
    ];
    
    // Setup mock BEFORE each test
    setupMock();
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('Test Delivery Fee', async () => {
    //ACT: Call the page
    render(
      <OrderContext.Provider value={{ orderName, orderItems }}>
        <Order />
      </OrderContext.Provider>
    );

    //ASSERT: Check for subtotal and delivery fee
    await waitFor(() => {
      expect(screen.getAllByText('$2.50')).toHaveLength(1);
    });
    expect(screen.getAllByText('$5.00')).toHaveLength(1);
  });

  it('Test Update Delivery Fee', async () => {
    //ACT: Call the page
    render(
      <OrderContext.Provider value={{ orderName, orderItems }}>
        <Order />
      </OrderContext.Provider>
    );

    //ACT: Update the Delivery distance by choosing the 5 mile option
    await userEvent.selectOptions(
      screen.getByRole('combobox'),
      screen.getByRole('option', { name: '5 miles' })
    );

    //ASSERT: Wait for the delivery fee to be updated
    await waitFor(() => {
      expect(screen.getAllByText('$5.00')).toHaveLength(2);
    });
    expect(screen.getAllByText('$0.86')).toHaveLength(1);
    expect(screen.getAllByText('$10.86')).toHaveLength(1);
  });
});

const setupMock = () => {
  const mockGet = jest.spyOn(axios, 'get');
  mockGet.mockImplementation((url) => {
    switch (url) {
      case `${API_URL}/api/delivery/test-fun/0`:
        return Promise.resolve({
          data: { status: 'success', data: 2.5 },
        });
      case `${API_URL}/api/delivery/test-fun/5`:
        return Promise.resolve({
          data: { status: 'success', data: 5.0 },
        });
      case `${API_URL}/api/subtotal/test-fun`:
        return Promise.resolve({
          data: { status: 'success', data: 5 },
        });
      case `${API_URL}/api/tax/test-fun/5`:
        return Promise.resolve({
          data: { status: 'success', data: 0.86 },
        });
      case `${API_URL}/api/tax/test-fun/0`:
        return Promise.resolve({
          data: { status: 'success', data: 0.43 },
        });
      case `${API_URL}/api/total/test-fun/5`:
        return Promise.resolve({
          data: { status: 'success', data: 10.86 },
        });
      case `${API_URL}/api/total/test-fun/0`:
        return Promise.resolve({
          data: { status: 'success', data: 5.43 },
        });
      default:
        return Promise.resolve({
          data: { status: 'fail' },
        });
    }
  });
};
